<a href="https://colab.research.google.com/github/faisalhamza909-blip/mental-health-clustering-case-study-/blob/main/mental_health_case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
import pandas as pd
path = "/content/drive/MyDrive/case study/mental-heath-in-tech-2016_20161114.csv"
df = pd.read_csv(path)

In [6]:
df.shape

(1433, 63)

we have 1433 rows and 63 columns

In [11]:
df.head

,Are you self-employed?,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health concerns and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:",...,"If you have a mental health issue, do you feel that it interferes with your work when being treated effectively?","If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?",What is your age?,What is your gender?,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,Which of the following best describes your work position?,Do you work remotely?
0,0,26-100,1.0,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,...,Not applicable to me,Not applicable to me,39,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
1,0,6-25,1.0,NaN,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
2,0,6-25,1.0,NaN,No,NaN,No,No,I don't know,Neither easy nor difficult,...,Not applicable to me,Not applicable to me,38,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Sometimes,43,male,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes
4,0,6-25,0.0,1.0,Yes,Yes,No,No,No,Neither easy nor difficult,...,Sometimes,Sometimes,43,Female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1433 entries, 0 to 1432
Data columns (total 63 columns):
 #   Column                                                                                                                                                                            Non-Null Count  Dtype
---  ------                                                                                                                                                                            --------------  -----
 0   Are you self-employed?                                                                                                                                                            1433 non-null   int64
 1   How many employees does your company or organization have?                                                                                                                        1146 non-null   object
 2   Is your employer primarily a tech company/organization?                                                                                                                           1146 non-null   float64
 3   Is your primary role within your company related to tech/IT?                                                                                                                      263 non-null    float64
 4   Does your employer provide mental health benefits as part of healthcare coverage?                                                                                                 1146 non-null   object
 5   Do you know the options for mental health care available under your employer-provided coverage?                                                                                   1013 non-null   object
 6   Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?                                            1146 non-null   object
 7   Does your employer offer resources to learn more about mental health concerns and options for seeking help?                                                                       1146 non-null   object
 8   Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?                                    1146 non-null   object
 9   If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:                                                                       1146 non-null   object
 10  Do you think that discussing a mental health disorder with your employer would have negative consequences?                                                                        1146 non-null   object
 11  Do you think that discussing a physical health issue with your employer would have negative consequences?                                                                         1146 non-null   object
 12  Would you feel comfortable discussing a mental health disorder with your coworkers?                                                                                               1146 non-null   object
 13  Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?                                                                                    1146 non-null   object
 14  Do you feel that your employer takes mental health as seriously as physical health?                                                                                               1146 non-null   object
 15  Have you heard of or observed negative consequences for co-workers who have been open about mental health issues in your workplace?                                               1146 non-null   object
 16  Do you have medical coverage (private insurance or state-provided) which includes treatment of  mental health issues?                                                             287 non-null    float64
 17  Do you know local or online resources to seek help for a mental health disorder?                                                                                                  287 non-null    object
 18  If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?                                                      287 non-null    object
 19  If you have revealed a mental health issue to a client or business contact, do you believe this has impacted you negatively?                                                      144 non-null    object
 20  If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?                                                            287 non-null    object
 21  If you have revealed a mental health issue to a coworker or employee, do you believe this has impacted you negatively?                                                            287 non-null    object
 22  Do you believe your productivity is ever affected by a mental health issue?                                                                                                       287 non-null    object
 23  If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?                                              204 non-null    object
 24  Do you have previous employers?                                                                                                                                                   1433 non-null   int64
 25  Have your previous employers provided mental health benefits?                                                                                                                     1264 non-null   object
 26  Were you aware of the options for mental health care provided by your previous employers?                                                                                         1264 non-null   object
 27  Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?                                                 1264 non-null   object
 28  Did your previous employers provide resources to learn more about mental health issues and how to seek help?                                                                      1264 non-null   object
 29  Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?                                      1264 non-null   object
 30  Do you think that discussing a mental health disorder with previous employers would have negative consequences?                                                                   1264 non-null   object
 31  Do you think that discussing a physical health issue with previous employers would have negative consequences?                                                                    1264 non-null   object
 32  Would you have been willing to discuss a mental health issue with your previous co-workers?                                                                                       1264 non-null   object
 33  Would you have been willing to discuss a mental health issue with your direct supervisor(s)?                                                                                      1264 non-null   object
 34  Did you feel that your previous employers took mental health as seriously as physical health?                                                                                     1264 non-null   object
 35  Did you hear of or observe negative consequences for co-workers with mental health issues in your previous workplaces?                                                            1264 non-null   object
 36  Would you be willing to bring up a physical health issue with a potential employer in an interview?                                                                               1433 non-null   object
 37  Why or why not?                                                                                                                                                                   1095 non-null   object
 38  Would you bring up a mental health issue with a potential employer in an interview?                                                                                               1433 non-null   object
 39  Why or why not?.1                                                                                                                                                                 1126 non-null   object
 40  Do you feel that being identified as a person with a mental health issue would hurt your career?                                                                                  1433 non-null   object
 41  Do you think that team members/co-workers would view you more negatively if they knew you suffered from a mental health issue?                                                    1433 non-null   object
 42  How willing would you be to share with friends and family that you have a mental illness?                                                                                         1433 non-null   object
 43  Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?                                        1344 non-null   object
 44  Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?  657 non-null    object
 45  Do you have a family history of mental illness?                                                                                                                                   1433 non-null   object
 46  Have you had a mental health disorder in the past?                                                                                                                                1433 non-null   object
 47  Do you currently have a mental health disorder?                                                                                                                                   1433 non-null   object
 48  If yes, what condition(s) have you been diagnosed with?                                                                                                                           568 non-null    object
 49  If maybe, what condition(s) do you believe you have?                                                                                                                              322 non-null    object
 50  Have you been diagnosed with a mental health condition by a medical professional?                                                                                                 1433 non-null   object
 51  If so, what condition(s) were you diagnosed with?                                                                                                                                 711 non-null    object
 52  Have you ever sought treatment for a mental health issue from a mental health professional?                                                                                       1433 non-null   int64
 53  If you have a mental health issue, do you feel that it interferes with your work when being treated effectively?                                                                  1433 non-null   object
 54  If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?                                                              1433 non-null   object
 55  What is your age?                                                                                                                                                                 1433 non-null   int64
 56  What is your gender?                                                                                                                                                              1430 non-null   object
 57  What country do you live in?                                                                                                                                                      1433 non-null   object
 58  What US state or territory do you live in?                                                                                                                                        840 non-null    object
 59  What country do you work in?                                                                                                                                                      1433 non-null   object
 60  What US state or territory do you work in?                                                                                                                                        851 non-null    object
 61  Which of the following best describes your work position?                                                                                                                         1433 non-null   object
 62  Do you work remotely?                                                                                                                                                             1433 non-null   object
dtypes: float64(3), int64(4), object(56)
memory usage: 705.4+ KB

Now we need to calculate the percentage of missing answers for each survey to see which column may neeed to be dropped or handled specially

In [23]:
missing_values = df.isnull()
mean_of_missing_values = missing_values.mean()
missing_percentage = mean_of_missing_values * 100

In [21]:
missing_percentage = missing_percentage.sort_values(ascending = False)
missing_percentage.head(15).round(1)

If you have revealed a mental health issue to a client or business contact, do you believe this has impacted you negatively?                                                        90.0
If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?                                                85.8
Is your primary role within your company related to tech/IT?                                                                                                                        81.6
Do you have medical coverage (private insurance or state-provided) which includes treatment of  mental health issues?                                                               80.0
If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?                                                        80.0
If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?                                                              80.0
If you have revealed a mental health issue to a coworker or employee, do you believe this has impacted you negatively?                                                              80.0
Do you know local or online resources to seek help for a mental health disorder?                                                                                                    80.0
Do you believe your productivity is ever affected by a mental health issue?                                                                                                         80.0
If maybe, what condition(s) do you believe you have?                                                                                                                                77.5
If yes, what condition(s) have you been diagnosed with?                                                                                                                             60.4
Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?    54.2
If so, what condition(s) were you diagnosed with?                                                                                                                                   50.4
What US state or territory do you live in?                                                                                                                                          41.4
What US state or territory do you work in?                                                                                                                                          40.6
dtype: float64

The table that we get after runnign above shows that columns with very high missing values are mostly caused by the survey's conditional structure (for example, questions only shown to self-employed respondents). Since these are missing due to the survey's nature, they will be dropped or filtered later on.

In [28]:
print(f"Column with more than 50% missing values: {(missing_percentage > 50).sum()}")
print(f"Column with no missing values: {(missing_percentage == 0).sum()}")

Column with more than 50% missing values: 13
Column with no missing values: 19

# **Gender**

In [46]:
gender = df["What is your gender?"]
unique_genders = gender.unique()
# print(unique_genders)
print(f"Number of unique genders: {gender.nunique()}")
print(f"Missing values: {gender.isnull().sum()}")
gender.value_counts().head(20)

Number of unique genders: 70
Missing values: 3

What is your gender?
Male          610
male          249
Female        153
female         95
M              86
m              79
F              38
f              23
Male           11
Female          9
woman           4
non-binary      4
Woman           3
female          3
man             3
Male (cis)      2
Man             2
Agender         2
Nonbinary       2
male            2
Name: count, dtype: int64

The output shows that the gender column contains 70 different answer and 3 missing values, although many of them mean the same thing. For example, "Male","male","M" all refer to male and some even contain hidden spaces.

# **AGE**

In [47]:
age = df["What is your age?"]
age.describe()

count    1433.000000
mean       34.286113
std        11.290931
min         3.000000
25%        28.000000
50%        33.000000
75%        39.000000
max       323.000000
Name: What is your age?, dtype: float64

In [53]:
unrealistic_ages = age[(age < 16) | (age>75)]
print(f"Number of unrealistic ages : {len(unrealistic_ages)}")
print(unrealistic_ages)

Number of unrealistic ages : 4
372     99
564    323
656      3
808     15
Name: What is your age?, dtype: int64

The age column has no missing values and the median age is 33 with most common age between 28 and 39. A few valus are unrealistic. They are most likely errors or typos or too young for regular employment. It is also very unlikely that somebody below the age of 16 would work in a tech company while 17 year olds could plausibly be interns or work voluntarily.